runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2|json))
  static_files: ../web/build/\1
  upload: ../web/build/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2|json))

- url: /.*
  static_files: ../web/build/index.html
  upload: ../web/build/index.html
  secure: always

skip_files:
- ../web/node_modules/*
- ../web/public/*
- ../web/src/*
- ../web/package.json
- ../web/README.md
- ../web/yarn.lock